<?php

/**
 * Currency information
 * 
 * Returns an array of countries for each currency.
 *
 * @package \i18n
 */

return [
	'AED' => ['ar_AE'],
	'AFN' => ['fa_AF'],
	'ALL' => ['sq_AL'],
	'AMD' => ['hy_AM'],
	'ANG' => ['nl_AN', 'en_AN'],
	'AOA' => ['pt_AO'],
	'ARS' => ['es_AR'],
	'AUD' => ['en_AU', 'en_CC', 'en_CX', 'en_HM', 'en_NF'],
	'AWG' => ['nl_AW'],
	'AZN' => ['az_AZ'],
	'BAM' => ['bs_BA'],
	'BBD' => ['en_BB'],
	'BDT' => ['bn_BD'],
	'BGN' => ['bg_BG'],
	'BHD' => ['ar_BH'],
	'BIF' => ['rn_BI', 'fr_BI'],
	'BMD' => ['en_BM'],
	'BND' => ['ms_BN'],
	'BOB' => ['es_BO'],
	'BRL' => ['pt_BR'],
	'BSD' => ['en_BS'],
	'BTN' => ['dz_BT'],
	'BWP' => ['en_BW', 'tn_BW'],
	'BYN' => ['be_BY', 'ru_BY'],
	'BZD' => ['en_BZ'],
	'CAD' => ['en_CA', 'fr_CA'],
	'CDF' => ['fr_CD'],
	'CHF' => ['de_CH', 'fr_CH', 'it_CH', 'rm_CH', 'de_LI'],
	'CLP' => ['es_CL'],
	'CNY' => ['zh_CN'],
	'COP' => ['es_CO'],
	'CRC' => ['es_CR'],
	'CUC' => ['es_CU'],
	'CUP' => ['es_CU'],
	'CVE' => ['pt_CV'],
	'CZK' => ['cs_CZ'],
	'DJF' => ['fr_DJ', 'ar_DJ'],
	'DKK' => ['da_DK', 'da_GL', 'da_FO'],
	'DOP' => ['es_DO'],
	'DZD' => ['ar_DZ'],
	'EGP' => ['ar_EG'],
	'ERN' => ['ti_ER'],
	'ETB' => ['am_ET'],
	'EUR' => [
		'de_DE', 'fr_FR', 'it_IT', 'es_ES', 'nl_NL', 'de_AT', 'de_BE', 'fr_BE',
		'fi_FI', 'pt_PT', 'el_GR', 'sk_SK', 'sl_SI', 'en_IE', 'ga_IE', 'et_EE',
		'lv_LV', 'lt_LT', 'fr_LU', 'de_LU', 'mt_MT', 'en_MT', 'nl_BE', 'ca_AD',
		'fr_MC', 'it_SM', 'it_VA', 'ca_ES', 'eu_ES', 'gl_ES', 'fr_GF', 'fr_GP',
		'fr_MQ', 'fr_RE', 'fr_YT', 'fr_PM', 'fr_BL', 'fr_MF', 'pt_PT', 'de_LU'
	],
	'FJD' => ['en_FJ'],
	'FKP' => ['en_FK'],
	'GBP' => ['en_GB', 'en_GG', 'en_IM', 'en_JE'],
	'GEL' => ['ka_GE'],
	'GGP' => ['en_GG'],
	'GHS' => ['en_GH'],
	'GIP' => ['en_GI'],
	'GMD' => ['en_GM'],
	'GNF' => ['fr_GN'],
	'GTQ' => ['es_GT'],
	'GYD' => ['en_GY'],
	'HKD' => ['zh_HK', 'en_HK'],
	'HNL' => ['es_HN'],
	'HRK' => ['hr_HR'],
	'HTG' => ['fr_HT', 'ht_HT'],
	'HUF' => ['hu_HU'],
	'IDR' => ['id_ID'],
	'ILS' => ['he_IL', 'ar_IL'],
	'IMP' => ['en_IMP'],
	'INR' => ['en_IN', 'hi_IN'],
	'IQD' => ['ar_IQ', 'ku_IQ'],
	'IRR' => ['fa_IR'],
	'ISK' => ['is_IS'],
	'JEP' => ['en_JEP'],
	'JMD' => ['en_JM'],
	'JOD' => ['ar_JO'],
	'JPY' => ['ja_JP'],
	'KES' => ['sw_KE', 'en_KE'],
	'KGS' => ['ky_KG', 'ru_KG'],
	'KHR' => ['km_KH'],
	'KMF' => ['ar_KM', 'fr_KM'],
	'KPW' => ['ko_KP'],
	'KRW' => ['ko_KR'],
	'KWD' => ['ar_KW'],
	'KYD' => ['en_KY'],
	'KZT' => ['kk_KZ', 'ru_KZ'],
	'LAK' => ['lo_LA'],
	'LBP' => ['ar_LB', 'fr_LB'],
	'LKR' => ['si_LK', 'ta_LK'],
	'LRD' => ['en_LR'],
	'LSL' => ['en_LS', 'st_LS'],
	'LYD' => ['ar_LY'],
	'MAD' => ['ar_MA', 'fr_MA', 'ar_EH'],
	'MDL' => ['ro_MD'],
	'MGA' => ['mg_MG', 'fr_MG'],
	'MKD' => ['mk_MK'],
	'MMK' => ['my_MM'],
	'MNT' => ['mn_MN'],
	'MOP' => ['zh_MO', 'pt_MO'],
	'MRU' => ['ar_MR'],
	'MUR' => ['en_MU', 'fr_MU'],
	'MVR' => ['dv_MV'],
	'MWK' => ['en_MW', 'ny_MW'],
	'MXN' => ['es_MX'],
	'MYR' => ['ms_MY'],
	'MZN' => ['pt_MZ'],
	'NAD' => ['en_NA', 'af_NA', 'de_NA'],
	'NGN' => ['en_NG'],
	'NIO' => ['es_NI'],
	'NOK' => ['no_NO', 'nb_NO', 'nn_NO', 'no_SJ', 'no_BV'],
	'NPR' => ['ne_NP'],
	'NZD' => ['en_NZ', 'en_CK', 'en_NU', 'en_TK', 'en_PN'],
	'OMR' => ['ar_OM'],
	'PAB' => ['es_PA'],
	'PEN' => ['es_PE'],
	'PGK' => ['en_PG'],
	'PHP' => ['en_PH', 'tl_PH'],
	'PKR' => ['en_PK', 'ur_PK'],
	'PLN' => ['pl_PL'],
	'PYG' => ['es_PY', 'gn_PY'],
	'QAR' => ['ar_QA'],
	'RON' => ['ro_RO'],
	'RSD' => ['sr_RS'],
	'RUB' => ['ru_RU'],
	'RWF' => ['rw_RW', 'fr_RW', 'en_RW'],
	'SAR' => ['ar_SA'],
	'SBD' => ['en_SB'],
	'SCR' => ['en_SC', 'fr_SC'],
	'SDG' => ['ar_SD', 'en_SD'],
	'SEK' => ['sv_SE'],
	'SGD' => ['en_SG', 'zh_SG', 'ms_SG', 'ta_SG'],
	'SHP' => ['en_SH'],
	'SLL' => ['en_SL'],
	'SOS' => ['so_SO', 'ar_SO'],
	'SRD' => ['nl_SR'],
	'SSP' => ['en_SS'],
	'STN' => ['pt_ST'],
	'SVC' => ['es_SV'],
	'SYP' => ['ar_SY'],
	'SZL' => ['en_SZ', 'ss_SZ'],
	'THB' => ['th_TH'],
	'TJS' => ['tg_TJ'],
	'TMT' => ['tk_TM'],
	'TND' => ['ar_TN'],
	'TOP' => ['to_TO'],
	'TRY' => ['tr_TR'],
	'TTD' => ['en_TT'],
	'TWD' => ['zh_TW'],
	'TZS' => ['sw_TZ', 'en_TZ'],
	'UAH' => ['uk_UA'],
	'UGX' => ['en_UG', 'sw_UG'],
	'USD' => [
		'en_US', 'es_US', 'en_AS', 'en_GU', 'en_MP', 'en_PR', 'en_UM', 'en_VI',
		'en_IO', 'en_VG', 'en_TC', 'en_BM', 'en_BQ', 'en_EC', 'en_SV', 'en_PW',
		'en_FM', 'en_MH', 'en_TL'
	],
	'UYU' => ['es_UY'],
	'UZS' => ['uz_UZ'],
	'VES' => ['es_VE'],
	'VND' => ['vi_VN'],
	'VUV' => ['bi_VU', 'en_VU', 'fr_VU'],
	'WST' => ['sm_WS', 'en_WS'],
	'XAF' => ['fr_CF', 'fr_TD', 'fr_GQ', 'fr_GA', 'fr_CM', 'fr_CG'],
	'XCD' => ['en_AG', 'en_DM', 'en_GD', 'en_KN', 'en_LC', 'en_VC', 'en_AI', 'en_MS'],
	'XOF' => ['fr_BJ', 'fr_BF', 'fr_CI', 'fr_GW', 'fr_ML', 'fr_NE', 'fr_SN', 'fr_TG'],
	'XPF' => ['fr_PF', 'fr_NC', 'fr_WF'],
	'YER' => ['ar_YE'],
	'ZAR' => ['en_ZA', 'af_ZA', 'zu_ZA', 'xh_ZA', 'en_NA', 'en_LS', 'en_SZ'],
	'ZMW' => ['en_ZM'],
	'ZWL' => ['en_ZW'],
];
